http:
  listner:
    host: "localhost"
    port: "9082"
    path: "/travelOnTip/{service}"

mysql:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "nateyMahder@2022"
  database: "travelOnTip"
